;; -*- lexical-binding: t; -*-
(defun time/set-up-whitespace-handling ()
  (interactive)
  (whitespace-mode 1)
  (add-to-list 'write-file-functions 'delete-trailing-whitespace))

(add-hook 'tuareg-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'c++-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'c-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'simpc-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'emacs-lisp-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'java-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'lua-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'rust-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'scala-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'markdown-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'haskell-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'python-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'erlang-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'asm-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'fasm-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'go-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'nim-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'yaml-mode-hook 'time/set-up-whitespace-handling)
(add-hook 'porth-mode-hook 'time/set-up-whitespace-handling)

(provide 'setup-whitespace)
